module Evergreen.Migrate.V2 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V1.Types
import Evergreen.V2.Types
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V2.Types.FrontendModel Evergreen.V2.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V2.Types.BackendModel Evergreen.V2.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V2.Types.FrontendMsg Evergreen.V2.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V2.Types.ToBackend Evergreen.V2.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V2.Types.BackendMsg Evergreen.V2.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V2.Types.ToFrontend Evergreen.V2.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V1.Types.BackendModel -> Evergreen.V2.Types.BackendModel
migrate_Types_BackendModel old =
    { rooms = old.rooms |> Dict.map (\k -> migrate_Types_Room)
    , clientToRoom = old.clientToRoom
    , statsViewers = old.statsViewers
    }


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V2.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = old.page |> migrate_Types_Page
    , roomData = old.roomData |> Maybe.map migrate_Types_Room
    , userName = old.userName
    , newRoomName = old.newRoomName
    , joinRoomId = old.joinRoomId
    , joinRoomPin = old.joinRoomPin
    , error = old.error
    , myClientId = old.myClientId
    , clipboardFeedback = old.clipboardFeedback
    , showShareLink = old.showShareLink
    , baseUrl = old.baseUrl
    , notifications = old.notifications
    , stats = old.stats
    }


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V2.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V2.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V2.Types.UrlChanged p0

        Evergreen.V1.Types.SetUserName p0 ->
            Evergreen.V2.Types.SetUserName p0

        Evergreen.V1.Types.SetNewRoomName p0 ->
            Evergreen.V2.Types.SetNewRoomName p0

        Evergreen.V1.Types.SetJoinRoomId p0 ->
            Evergreen.V2.Types.SetJoinRoomId p0

        Evergreen.V1.Types.SetJoinRoomPin p0 ->
            Evergreen.V2.Types.SetJoinRoomPin p0

        Evergreen.V1.Types.CreateRoomClicked ->
            Evergreen.V2.Types.CreateRoomClicked

        Evergreen.V1.Types.JoinRoomClicked ->
            Evergreen.V2.Types.JoinRoomClicked

        Evergreen.V1.Types.CastVote p0 ->
            Evergreen.V2.Types.CastVote (p0 |> migrate_Types_Vote)

        Evergreen.V1.Types.ClearVote ->
            Evergreen.V2.Types.ClearVote

        Evergreen.V1.Types.RevealVotesClicked ->
            Evergreen.V2.Types.RevealVotesClicked

        Evergreen.V1.Types.ResetVotesClicked ->
            Evergreen.V2.Types.ResetVotesClicked

        Evergreen.V1.Types.CopyShareLink ->
            Evergreen.V2.Types.CopyShareLink

        Evergreen.V1.Types.ToggleShareLink ->
            Evergreen.V2.Types.ToggleShareLink

        Evergreen.V1.Types.ClipboardResult p0 ->
            Evergreen.V2.Types.ClipboardResult p0

        Evergreen.V1.Types.ClearClipboardFeedback ->
            Evergreen.V2.Types.ClearClipboardFeedback

        Evergreen.V1.Types.RefreshStats ->
            Evergreen.V2.Types.RefreshStats

        Evergreen.V1.Types.NoOpFrontendMsg ->
            Evergreen.V2.Types.NoOpFrontendMsg


migrate_Types_Page : Evergreen.V1.Types.Page -> Evergreen.V2.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V1.Types.HomePage ->
            Evergreen.V2.Types.HomePage

        Evergreen.V1.Types.RoomPage p0 p1 ->
            Evergreen.V2.Types.RoomPage p0 p1

        Evergreen.V1.Types.StatsPage ->
            Evergreen.V2.Types.StatsPage


migrate_Types_Participant : Evergreen.V1.Types.Participant -> Evergreen.V2.Types.Participant
migrate_Types_Participant old =
    { name = old.name
    , vote = old.vote |> Maybe.map migrate_Types_Vote
    , isConnected = old.isConnected
    , missedPongs = old.missedPongs
    }


migrate_Types_Room : Evergreen.V1.Types.Room -> Evergreen.V2.Types.Room
migrate_Types_Room old =
    { id = old.id
    , pin = old.pin
    , name = old.name
    , participants = old.participants |> Dict.map (\k -> migrate_Types_Participant)
    , votesRevealed = old.votesRevealed
    }


migrate_Types_Stats : Evergreen.V1.Types.Stats -> Evergreen.V2.Types.Stats
migrate_Types_Stats old =
    old


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V2.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.CreateRoom p0 p1 ->
            Evergreen.V2.Types.CreateRoom p0 p1

        Evergreen.V1.Types.JoinRoom p0 p1 p2 ->
            Evergreen.V2.Types.JoinRoom p0 p1 p2

        Evergreen.V1.Types.SubmitVote p0 ->
            Evergreen.V2.Types.SubmitVote (p0 |> migrate_Types_Vote)

        Evergreen.V1.Types.ClearMyVote ->
            Evergreen.V2.Types.ClearMyVote

        Evergreen.V1.Types.RevealVotes ->
            Evergreen.V2.Types.RevealVotes

        Evergreen.V1.Types.ResetVotes ->
            Evergreen.V2.Types.ResetVotes

        Evergreen.V1.Types.LeaveRoom ->
            Evergreen.V2.Types.LeaveRoom

        Evergreen.V1.Types.SubscribeToStats ->
            Evergreen.V2.Types.SubscribeToStats

        Evergreen.V1.Types.UnsubscribeFromStats ->
            Evergreen.V2.Types.UnsubscribeFromStats

        Evergreen.V1.Types.Pong ->
            Evergreen.V2.Types.Pong


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V2.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.RoomCreated p0 p1 ->
            Evergreen.V2.Types.RoomCreated (p0 |> migrate_Types_Room) p1

        Evergreen.V1.Types.RoomJoined p0 p1 ->
            Evergreen.V2.Types.RoomJoined (p0 |> migrate_Types_Room) p1

        Evergreen.V1.Types.RoomUpdated p0 ->
            Evergreen.V2.Types.RoomUpdated (p0 |> migrate_Types_Room)

        Evergreen.V1.Types.RoomNotFound ->
            Evergreen.V2.Types.RoomNotFound

        Evergreen.V1.Types.InvalidPin ->
            Evergreen.V2.Types.InvalidPin

        Evergreen.V1.Types.RoomClosed ->
            Evergreen.V2.Types.RoomClosed

        Evergreen.V1.Types.ErrorMessage p0 ->
            Evergreen.V2.Types.ErrorMessage p0

        Evergreen.V1.Types.StatsData p0 ->
            Evergreen.V2.Types.StatsData (p0 |> migrate_Types_Stats)

        Evergreen.V1.Types.Ping ->
            Evergreen.V2.Types.Ping

        Evergreen.V1.Types.UserTimedOut p0 ->
            Evergreen.V2.Types.UserTimedOut p0


migrate_Types_Vote : Evergreen.V1.Types.Vote -> Evergreen.V2.Types.Vote
migrate_Types_Vote old =
    case old of
        Evergreen.V1.Types.NumericVote p0 ->
            Evergreen.V2.Types.NumericVote p0

        Evergreen.V1.Types.QuestionMark ->
            Evergreen.V2.Types.QuestionMark

        Evergreen.V1.Types.CoffeeBreak ->
            Evergreen.V2.Types.CoffeeBreak
