module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - placeholder values wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V3.Types
import Evergreen.V4.Types
import Lamdera.Migrations exposing (ModelMigration(..), MsgMigration(..))
import Maybe
import Set


frontendModel : Evergreen.V3.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V3.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V3.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V3.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V3.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V3.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V3.Types.BackendModel -> Evergreen.V4.Types.BackendModel
migrate_Types_BackendModel old =
    { rooms = old.rooms |> Dict.map (\_ room -> migrate_Types_Room room)
    , clientToRoom = old.clientToRoom
    , statsViewers =
        old.statsViewers
            |> Set.toList
            |> List.map (\clientId -> ( clientId, defaultStatsFilters ))
            |> Dict.fromList
    , activeSessionStats = Dict.empty
    , completedSessionsByDay = Dict.empty
    , currentDayKey = "1970-01-01"
    , currentDayIndex = 0
    }


migrate_Types_FrontendModel : Evergreen.V3.Types.FrontendModel -> Evergreen.V4.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = old.page |> migrate_Types_Page
    , roomData = old.roomData |> Maybe.map migrate_Types_Room
    , userName = old.userName
    , newRoomName = old.newRoomName
    , joinRoomId = old.joinRoomId
    , joinRoomPin = old.joinRoomPin
    , error = old.error
    , myClientId = old.myClientId
    , clipboardFeedback = old.clipboardFeedback
    , showShareLink = old.showShareLink
    , baseUrl = old.baseUrl
    , notifications = old.notifications
    , stats = old.stats |> Maybe.map migrate_Types_Stats
    , statsFilters = defaultStatsFilters
    }


migrate_Types_BackendMsg : Evergreen.V3.Types.BackendMsg -> Evergreen.V4.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V3.Types.ClientConnected p0 p1 ->
            Evergreen.V4.Types.ClientConnected p0 p1

        Evergreen.V3.Types.ClientDisconnected p0 p1 ->
            Evergreen.V4.Types.ClientDisconnected p0 p1

        Evergreen.V3.Types.PingTick ->
            Evergreen.V4.Types.NoOpBackendMsg

        Evergreen.V3.Types.NoOpBackendMsg ->
            Evergreen.V4.Types.NoOpBackendMsg


migrate_Types_FrontendMsg : Evergreen.V3.Types.FrontendMsg -> Evergreen.V4.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V3.Types.UrlClicked p0 ->
            Evergreen.V4.Types.UrlClicked p0

        Evergreen.V3.Types.UrlChanged p0 ->
            Evergreen.V4.Types.UrlChanged p0

        Evergreen.V3.Types.SetUserName p0 ->
            Evergreen.V4.Types.SetUserName p0

        Evergreen.V3.Types.SetNewRoomName p0 ->
            Evergreen.V4.Types.SetNewRoomName p0

        Evergreen.V3.Types.SetJoinRoomId p0 ->
            Evergreen.V4.Types.SetJoinRoomId p0

        Evergreen.V3.Types.SetJoinRoomPin p0 ->
            Evergreen.V4.Types.SetJoinRoomPin p0

        Evergreen.V3.Types.CreateRoomClicked ->
            Evergreen.V4.Types.CreateRoomClicked

        Evergreen.V3.Types.JoinRoomClicked ->
            Evergreen.V4.Types.JoinRoomClicked

        Evergreen.V3.Types.CastVote p0 ->
            Evergreen.V4.Types.CastVote (p0 |> migrate_Types_Vote)

        Evergreen.V3.Types.ClearVote ->
            Evergreen.V4.Types.ClearVote

        Evergreen.V3.Types.RevealVotesClicked ->
            Evergreen.V4.Types.RevealVotesClicked

        Evergreen.V3.Types.ResetVotesClicked ->
            Evergreen.V4.Types.ResetVotesClicked

        Evergreen.V3.Types.CopyShareLink ->
            Evergreen.V4.Types.CopyShareLink

        Evergreen.V3.Types.ToggleShareLink ->
            Evergreen.V4.Types.ToggleShareLink

        Evergreen.V3.Types.ClipboardResult p0 ->
            Evergreen.V4.Types.ClipboardResult p0

        Evergreen.V3.Types.ClearClipboardFeedback ->
            Evergreen.V4.Types.ClearClipboardFeedback

        Evergreen.V3.Types.RefreshStats ->
            Evergreen.V4.Types.RefreshStats

        Evergreen.V3.Types.TabBecameVisible ->
            Evergreen.V4.Types.TabBecameVisible

        Evergreen.V3.Types.TabBecameHidden ->
            Evergreen.V4.Types.TabBecameHidden

        Evergreen.V3.Types.NoOpFrontendMsg ->
            Evergreen.V4.Types.NoOpFrontendMsg


migrate_Types_Page : Evergreen.V3.Types.Page -> Evergreen.V4.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V3.Types.HomePage ->
            Evergreen.V4.Types.HomePage

        Evergreen.V3.Types.RoomPage p0 p1 ->
            Evergreen.V4.Types.RoomPage p0 p1

        Evergreen.V3.Types.StatsPage ->
            Evergreen.V4.Types.StatsPage


migrate_Types_Participant : Evergreen.V3.Types.Participant -> Evergreen.V4.Types.Participant
migrate_Types_Participant old =
    { name = old.name
    , vote = old.vote |> Maybe.map migrate_Types_Vote
    , isConnected = old.isConnected
    , missedPongs = old.missedPongs
    , tabHidden = old.tabHidden
    , hiddenPingTicks = old.hiddenPingTicks
    }


migrate_Types_Room : Evergreen.V3.Types.Room -> Evergreen.V4.Types.Room
migrate_Types_Room old =
    { id = old.id
    , pin = old.pin
    , name = old.name
    , participants = old.participants |> Dict.map (\_ participant -> migrate_Types_Participant participant)
    , votesRevealed = old.votesRevealed
    }


migrate_Types_Stats : Evergreen.V3.Types.Stats -> Evergreen.V4.Types.Stats
migrate_Types_Stats old =
    { filters = defaultStatsFilters
    , live = liveStatsFromLegacy old
    , recent = emptyHistoricalStats (Just defaultStatsFilters.recentDays)
    , allTime = emptyHistoricalStats Nothing
    }


migrate_Types_ToBackend : Evergreen.V3.Types.ToBackend -> Evergreen.V4.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V3.Types.CreateRoom p0 p1 ->
            Evergreen.V4.Types.CreateRoom p0 p1

        Evergreen.V3.Types.JoinRoom p0 p1 p2 ->
            Evergreen.V4.Types.JoinRoom p0 p1 p2

        Evergreen.V3.Types.SubmitVote p0 ->
            Evergreen.V4.Types.SubmitVote (p0 |> migrate_Types_Vote)

        Evergreen.V3.Types.ClearMyVote ->
            Evergreen.V4.Types.ClearMyVote

        Evergreen.V3.Types.RevealVotes ->
            Evergreen.V4.Types.RevealVotes

        Evergreen.V3.Types.ResetVotes ->
            Evergreen.V4.Types.ResetVotes

        Evergreen.V3.Types.LeaveRoom ->
            Evergreen.V4.Types.LeaveRoom

        Evergreen.V3.Types.SubscribeToStats ->
            Evergreen.V4.Types.SubscribeToStats defaultStatsFilters

        Evergreen.V3.Types.UnsubscribeFromStats ->
            Evergreen.V4.Types.UnsubscribeFromStats

        Evergreen.V3.Types.Pong ->
            Evergreen.V4.Types.Pong

        Evergreen.V3.Types.VisibilityPong ->
            Evergreen.V4.Types.VisibilityPong

        Evergreen.V3.Types.TabHidden ->
            Evergreen.V4.Types.TabHidden


migrate_Types_ToFrontend : Evergreen.V3.Types.ToFrontend -> Evergreen.V4.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V3.Types.RoomCreated p0 p1 ->
            Evergreen.V4.Types.RoomCreated (p0 |> migrate_Types_Room) p1

        Evergreen.V3.Types.RoomJoined p0 p1 ->
            Evergreen.V4.Types.RoomJoined (p0 |> migrate_Types_Room) p1

        Evergreen.V3.Types.RoomUpdated p0 ->
            Evergreen.V4.Types.RoomUpdated (p0 |> migrate_Types_Room)

        Evergreen.V3.Types.RoomNotFound ->
            Evergreen.V4.Types.RoomNotFound

        Evergreen.V3.Types.InvalidPin ->
            Evergreen.V4.Types.InvalidPin

        Evergreen.V3.Types.RoomClosed ->
            Evergreen.V4.Types.RoomClosed

        Evergreen.V3.Types.ErrorMessage p0 ->
            Evergreen.V4.Types.ErrorMessage p0

        Evergreen.V3.Types.StatsData p0 ->
            Evergreen.V4.Types.StatsData (p0 |> migrate_Types_Stats)

        Evergreen.V3.Types.Ping ->
            Evergreen.V4.Types.Ping

        Evergreen.V3.Types.UserTimedOut p0 ->
            Evergreen.V4.Types.UserTimedOut p0


migrate_Types_Vote : Evergreen.V3.Types.Vote -> Evergreen.V4.Types.Vote
migrate_Types_Vote old =
    case old of
        Evergreen.V3.Types.NumericVote p0 ->
            Evergreen.V4.Types.NumericVote p0

        Evergreen.V3.Types.HalfPoint ->
            Evergreen.V4.Types.HalfPoint

        Evergreen.V3.Types.QuestionMark ->
            Evergreen.V4.Types.QuestionMark

        Evergreen.V3.Types.CoffeeBreak ->
            Evergreen.V4.Types.CoffeeBreak


defaultStatsFilters : Evergreen.V4.Types.StatsFilters
defaultStatsFilters =
    { recentDays = 7
    , minParticipants = 1
    , minVotes = 1
    }


emptyHistoricalStats : Maybe Int -> Evergreen.V4.Types.HistoricalStats
emptyHistoricalStats maybeWindowDays =
    { windowDays = maybeWindowDays
    , sessionCount = 0
    , completedSessionCount = 0
    , totalVotes = 0
    , averageParticipants = 0
    , averageVotes = 0
    , revealRate = 0
    , cardPercentages = []
    , roomSizeBuckets =
        [ { label = "1", sessionCount = 0 }
        , { label = "2-3", sessionCount = 0 }
        , { label = "4-6", sessionCount = 0 }
        , { label = "7+", sessionCount = 0 }
        ]
    , sessionsByDay = []
    }


liveStatsFromLegacy : Evergreen.V3.Types.Stats -> Evergreen.V4.Types.LiveStats
liveStatsFromLegacy old =
    { activeRooms = old.totalRooms
    , connectedUsers = old.totalConnectedClients
    , awayUsers =
        old.rooms
            |> List.concatMap .participants
            |> List.filter (\participant -> participant.isConnected && participant.tabHidden)
            |> List.length
    , roomsVoting =
        old.rooms
            |> List.filter (\room -> not room.votesRevealed)
            |> List.length
    , roomsRevealed =
        old.rooms
            |> List.filter .votesRevealed
            |> List.length
    }
