module Evergreen.Migrate.V5 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V4.Types
import Evergreen.V5.Types
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V4.Types.FrontendModel -> ModelMigration Evergreen.V5.Types.FrontendModel Evergreen.V5.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V4.Types.BackendModel -> ModelMigration Evergreen.V5.Types.BackendModel Evergreen.V5.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V4.Types.FrontendMsg -> MsgMigration Evergreen.V5.Types.FrontendMsg Evergreen.V5.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V4.Types.ToBackend -> MsgMigration Evergreen.V5.Types.ToBackend Evergreen.V5.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V4.Types.BackendMsg -> MsgMigration Evergreen.V5.Types.BackendMsg Evergreen.V5.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V4.Types.ToFrontend -> MsgMigration Evergreen.V5.Types.ToFrontend Evergreen.V5.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V4.Types.FrontendModel -> Evergreen.V5.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = old.page |> migrate_Types_Page
    , themePreference = Evergreen.V5.Types.UseSystemTheme
    , systemTheme = Evergreen.V5.Types.LightTheme
    , activeTheme = Evergreen.V5.Types.LightTheme
    , roomData = old.roomData |> Maybe.map migrate_Types_Room
    , userName = old.userName
    , newRoomName = old.newRoomName
    , joinRoomId = old.joinRoomId
    , joinRoomPin = old.joinRoomPin
    , error = old.error
    , myClientId = old.myClientId
    , clipboardFeedback = old.clipboardFeedback
    , showShareLink = old.showShareLink
    , baseUrl = old.baseUrl
    , notifications = old.notifications
    , stats = old.stats
    , statsFilters = old.statsFilters |> migrate_Types_StatsFilters
    }


migrate_Types_FrontendMsg : Evergreen.V4.Types.FrontendMsg -> Evergreen.V5.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V4.Types.UrlClicked p0 ->
            Evergreen.V5.Types.UrlClicked p0

        Evergreen.V4.Types.UrlChanged p0 ->
            Evergreen.V5.Types.UrlChanged p0

        Evergreen.V4.Types.SetUserName p0 ->
            Evergreen.V5.Types.SetUserName p0

        Evergreen.V4.Types.SetNewRoomName p0 ->
            Evergreen.V5.Types.SetNewRoomName p0

        Evergreen.V4.Types.SetJoinRoomId p0 ->
            Evergreen.V5.Types.SetJoinRoomId p0

        Evergreen.V4.Types.SetJoinRoomPin p0 ->
            Evergreen.V5.Types.SetJoinRoomPin p0

        Evergreen.V4.Types.CreateRoomClicked ->
            Evergreen.V5.Types.CreateRoomClicked

        Evergreen.V4.Types.JoinRoomClicked ->
            Evergreen.V5.Types.JoinRoomClicked

        Evergreen.V4.Types.CastVote p0 ->
            Evergreen.V5.Types.CastVote (p0 |> migrate_Types_Vote)

        Evergreen.V4.Types.ClearVote ->
            Evergreen.V5.Types.ClearVote

        Evergreen.V4.Types.RevealVotesClicked ->
            Evergreen.V5.Types.RevealVotesClicked

        Evergreen.V4.Types.ResetVotesClicked ->
            Evergreen.V5.Types.ResetVotesClicked

        Evergreen.V4.Types.CopyShareLink ->
            Evergreen.V5.Types.CopyShareLink

        Evergreen.V4.Types.ToggleShareLink ->
            Evergreen.V5.Types.ToggleShareLink

        Evergreen.V4.Types.ClipboardResult p0 ->
            Evergreen.V5.Types.ClipboardResult p0

        Evergreen.V4.Types.ClearClipboardFeedback ->
            Evergreen.V5.Types.ClearClipboardFeedback

        Evergreen.V4.Types.RefreshStats ->
            Evergreen.V5.Types.RefreshStats

        Evergreen.V4.Types.SetStatsRecentDays p0 ->
            Evergreen.V5.Types.SetStatsRecentDays p0

        Evergreen.V4.Types.SetStatsMinParticipants p0 ->
            Evergreen.V5.Types.SetStatsMinParticipants p0

        Evergreen.V4.Types.SetStatsMinVotes p0 ->
            Evergreen.V5.Types.SetStatsMinVotes p0

        Evergreen.V4.Types.TabBecameVisible ->
            Evergreen.V5.Types.TabBecameVisible

        Evergreen.V4.Types.TabBecameHidden ->
            Evergreen.V5.Types.TabBecameHidden

        Evergreen.V4.Types.NoOpFrontendMsg ->
            Evergreen.V5.Types.NoOpFrontendMsg


migrate_Types_Page : Evergreen.V4.Types.Page -> Evergreen.V5.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V4.Types.HomePage ->
            Evergreen.V5.Types.HomePage

        Evergreen.V4.Types.RoomPage p0 p1 ->
            Evergreen.V5.Types.RoomPage p0 p1

        Evergreen.V4.Types.StatsPage ->
            Evergreen.V5.Types.StatsPage


migrate_Types_Participant : Evergreen.V4.Types.Participant -> Evergreen.V5.Types.Participant
migrate_Types_Participant old =
    { name = old.name
    , vote = old.vote |> Maybe.map migrate_Types_Vote
    , isConnected = old.isConnected
    , missedPongs = old.missedPongs
    , tabHidden = old.tabHidden
    , hiddenPingTicks = old.hiddenPingTicks
    }


migrate_Types_Room : Evergreen.V4.Types.Room -> Evergreen.V5.Types.Room
migrate_Types_Room old =
    { id = old.id
    , pin = old.pin
    , name = old.name
    , participants = old.participants |> Dict.map (\_ participant -> migrate_Types_Participant participant)
    , votesRevealed = old.votesRevealed
    }


migrate_Types_StatsFilters : Evergreen.V4.Types.StatsFilters -> Evergreen.V5.Types.StatsFilters
migrate_Types_StatsFilters old =
    old


migrate_Types_Vote : Evergreen.V4.Types.Vote -> Evergreen.V5.Types.Vote
migrate_Types_Vote old =
    case old of
        Evergreen.V4.Types.NumericVote p0 ->
            Evergreen.V5.Types.NumericVote p0

        Evergreen.V4.Types.HalfPoint ->
            Evergreen.V5.Types.HalfPoint

        Evergreen.V4.Types.QuestionMark ->
            Evergreen.V5.Types.QuestionMark

        Evergreen.V4.Types.CoffeeBreak ->
            Evergreen.V5.Types.CoffeeBreak
